version: '3.8'

services:
  clube-gestao:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clube-gestao
    restart: unless-stopped
    ports:
      - "58524:58524"  # Backend
      - "52348:52348"  # Frontend
    environment:
      - NODE_ENV=production
      - PORT=58524
      - FRONTEND_PORT=52348
    volumes:
      - clube-data:/app/data
    networks:
      - clube-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=clube-gestao
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - clube-network

networks:
  clube-network:
    driver: bridge

volumes:
  clube-data:
  mongodb-data: