name: Docker Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Setup Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.20.2'
        
      - name: Build and start containers
        run: |
          docker-compose build
          docker-compose up -d
          
      - name: Wait for services to start
        run: |
          echo "Waiting for services to start..."
          sleep 30
          
      - name: Check running containers
        run: docker-compose ps
        
      - name: Check backend logs
        run: docker-compose logs clube-gestao
        
      - name: Check MongoDB logs
        run: docker-compose logs mongodb
        
      - name: Run health check
        run: |
          # Update ports to match the ones in the .env file
          curl -f http://localhost:58524/ || echo "Backend not responding on port 58524"
          echo "Backend health check completed"
          curl -f http://localhost:52348/ || echo "Frontend not responding on port 52348"
          echo "Frontend health check completed"